{{- range $groupName, $group := dict "infra" .Values.infra "apps" .Values.apps "datastores" .Values.datastores }}
  {{- range $appName, $appCfg := $group }}
    {{- if $appCfg.enabled }}

      # Load base Application YAML from files/
      {{- $baseApp := (tpl (.Files.Get (printf "files/%s.yaml" $appName)) $) | fromYaml }}

      # If there are env-specific overrides, merge them at the top level
      {{- if and $appCfg.injectEnvSpecificOverride (hasKey $appCfg "override") }}
        {{- $baseApp = mergeOverwrite $baseApp $appCfg.override }}
      {{- end }}

      {{ toYaml $baseApp }}
      ---
    {{- end }}
  {{- end }}
{{- end }}
