---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auditservice-elastic-nodes # cannot be changed
spec:
  project: default # cannot be changed
  source:
    repoURL: git@github.com:your-org/helm.git
    path: auditservice-elastic-nodes
    targetRevision: main
    helm:
      valueFiles: 
        - values.yaml 
  destination:
    server: https://kubernetes.default.svc # cannot be changed
    namespace: elasticsearch
  syncPolicy:
    automated:
        selfHeal: true
    syncOptions:
      - CreateNamespace=true
  syncWave: 0
