envName: test-env
k8sAPIServer: https://653D0808A707D2D0DCCA8F8FDE7B2DE1.gr7.us-east-2.eks.amazonaws.com
cloud:
  provider: aws # bydeafult
  gcp:
    google-cas-issuer:
      infraApps:
        enabled: true
        injectEnvSpecificOverride: true
        name: testing 
        syncWave: 2 
        repoURL: https://kubernetes.com
        server: hello5.com
  aws:
    infraApps:
      aws-loadbalancer-controller:
        enabled: true
        injectEnvSpecificOverride: true
        multisource: true
        name: clustu
        syncWave: 9 
        sources:
         - chart: otel-integration
           helm:
             valueFiles:
               - $values/coralogix/values.yaml
               - $values/coralogix/values2.yaml
           repoURL: https://cgx.jfrog.io/artifactory/coralogix-charts-virtual
           targetRevision: 0.0.9
         - ref: values
           repoURL: git@github.com:skyflowapi/helm.git
           targetRevision: main 
argoApps:
  datastores:
    pgsql:
      enabled: true
      injectEnvSpecificOverride: true
      name: pgu
      syncWave: 10 
      repoURL: https://kubernetes.com
      server: ola5.com
