apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgsql
spec:
  project: default
  source:
    repoURL: git@github.com:your-org/helm.git
    path: pgsql
    targetRevision: main
    helm:
      valueFiles: []
  destination:
    server: https://kubernetes.default.svc
    namespace: pgsql
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
